[package]
name = "chameleon-hashing"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
encryption = { path = "../encryption" }
zkproofs = { path = "../zkproofs" }
rand_core = { workspace = true }
sha2 = { workspace = true } 
digest = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
criterion = "0.8.2"

[lib]
name = "chameleon_hashing"
path = "src/lib.rs"

[[bench]]
name = "chameleon_hashing_benchmarks"
path = "benches/benchmarks.rs"
harness = false
