[package]
name = "zkproofs"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
hashing = { path = "../hashing" } 
curve25519-dalek = { workspace = true }
rand_core = { workspace = true }
hybrid-array = { workspace = true }

[dev-dependencies]
sha2 = { workspace = true } 
rand = { workspace = true }
digest = { workspace = true }

[lib]
name = "zkproofs"
path = "src/lib.rs"
