name: Run CI tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  format_and_lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Update toolchain
      run: rustup update
    - name: Format
      run: cargo fmt --all --check
    - name: Clippy
      run: cargo clippy --all-targets --all-features

  build_and_test:
    needs: format_and_lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Update toolchain
      run: rustup update
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
